using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;

namespace Bacon.Generator;

internal static class IndentedTextWriterExtensions
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void OpenBracket(this IndentedTextWriter iw)
    {
        iw.WriteLine("{");
        ++iw.Indent;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static void CloseBracket(this IndentedTextWriter iw)
    {
        --iw.Indent;
        iw.WriteLine("}");
    }

    public static void WriteHeader(this IndentedTextWriter iw)
    {
        iw.WriteLine("// <auto-generated/>");
        iw.WriteLine($"// {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        iw.WriteLine("#nullable enable");
        iw.WriteLine();
    }

    public static void WriteNamespace(this IndentedTextWriter iw, string? @namespace)
    {
        if (!string.IsNullOrWhiteSpace(@namespace))
        {
            iw.WriteLine($"namespace {@namespace};");
            iw.WriteLine();
        }
    }
}